### ISSUE TITLE
MTD415L: do you have a serial protocol specs and C# exmples

### ISSUE THREAD

**Issue by sensboston** [Thorlabs/Current_And_Temperature_Controller_Examples#8]
Hello, could you please provide me a C# snippet how to read and set temperature for MTD415L controller?
I tried to use class MTDDevice from C:\Program Files (x86)\Thorlabs\MTDEVAL\Application\Thorlabs.MTDLib.dll 
but it returns incorrect values.
Also I found a bunch of serial protocol commands like (removed data = port.ReadLine();) :
```
                port.WriteLine("T?");
                ProcessData(device, MTDReadCommand.GetTemperature, data, logger);
                port.WriteLine("W?");
                ProcessData(device, MTDReadCommand.GetTemperatureWindow, data, logger);
                port.WriteLine("P?");
                ProcessData(device, MTDReadCommand.GetPCoefficient, data, logger);
                port.WriteLine("I?");
                ProcessData(device, MTDReadCommand.GetICoefficient, data, logger);
                port.WriteLine("D?");
                ProcessData(device, MTDReadCommand.GetDCoefficient, data, logger);
                port.WriteLine("C?");
                ProcessData(device, MTDReadCommand.GetCycleTime, data, logger);
                port.WriteLine("L?");
                ProcessData(device, MTDReadCommand.GetCurrentLimit, data, logger);
                port.WriteLine("d?");
                ProcessData(device, MTDReadCommand.GetTemperatureProtectionDelay, data, logger);
                port.WriteLine("G?");
                ProcessData(device, MTDReadCommand.GetCriticalGain, data, logger);
                port.WriteLine("O?");
                ProcessData(device, MTDReadCommand.GetCriticalPeriodDuration, data, logger);
```
and these commands return correct information but I can't find any Write or Set commands.
So if you can't provide me C# code, please provide a serial protocol description.

Thank you!

**Comment by gboedecker** [comment]
Hello, after installation of the software, you can find a C# example in C:\Program Files (x86)\IVI Foundation\VISA\WinNT\TLMTD\Examples\MS.NET_CS. 
The command documentation is in C:\Program Files (x86)\IVI Foundation\VISA\WinNT\TLMTD\Manual.
We provide a complete list of serial commands in the datasheet that can be downloaded from the website https://www.thorlabs.de/thorproduct.cfm?partnumber=MTD415L

**Comment by sensboston** [comment]
Perfect, thanks, it's exactly what I need!
